# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Base
mod_id=slopstrocity
mod_name=Slopstrocity
mod_license=MIT
mod_authors=Meme Man, LaDiamond
mod_description=WAITER! WAITER! MORE MONSTROCITIES WITH SPIT, SLAM, AND ROAR ATTACKS PLEASE! AND BASE ITS DESIGN OFF OF THE REDSTONE MONSTROCITY FROM MINECRAFT DUNGEONS!
mod_version=1.0.0
mod_group_id=dev.ploats
mod_logo_path=slopstrocity_logo.png
mod_display_url=
mod_auto_update_url=

mdg_plugin_version=2.0.146

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

neoforge_version=21.1.250
neoforge_version_range=[21.1.250,)

loader_version_range=[1,)